table olist_customers_dataset
	lineageTag: 9488aed6-2285-49e5-9405-290cce88fc3b

	column customer_id
		dataType: string
		lineageTag: e46b609e-4b3c-4347-9706-aaa5e3e7e2b1
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_unique_id
		dataType: string
		lineageTag: b4206d37-417e-4289-a12b-7fd91a8775ba
		summarizeBy: none
		sourceColumn: customer_unique_id

		annotation SummarizationSetBy = Automatic

	column customer_zip_code_prefix
		dataType: int64
		formatString: 0
		lineageTag: 75bf0647-dbd9-4b2d-8689-2ab47e893bf3
		summarizeBy: sum
		sourceColumn: customer_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column customer_city
		dataType: string
		lineageTag: d71b02b9-28c1-4207-95f7-85f4fb149d6d
		summarizeBy: none
		sourceColumn: customer_city

		annotation SummarizationSetBy = Automatic

	column customer_state
		dataType: string
		lineageTag: da17a605-0fff-4c9f-8a2b-ef9044282551
		summarizeBy: none
		sourceColumn: customer_state

		annotation SummarizationSetBy = Automatic

	partition olist_customers_dataset = m
		mode: import
		source =
				let
				  Źródło = Csv.Document(File.Contents("C:\Users\szyme\Desktop\archive\olist_customers_dataset.csv"), [Delimiter = ",", Columns = 5, QuoteStyle = QuoteStyle.None]),
				  #"Nagłówki o podwyższonym poziomie" = Table.PromoteHeaders(Źródło, [PromoteAllScalars = true]),
				  #"Zmieniono typ kolumny" = Table.TransformColumnTypes(#"Nagłówki o podwyższonym poziomie", {{"customer_id", type text}, {"customer_unique_id", type text}, {"customer_zip_code_prefix", Int64.Type}, {"customer_city", type text}, {"customer_state", type text}}, "pl")
				in
				  #"Zmieniono typ kolumny"

	annotation PBI_ResultType = Table

